### ISSUE TITLE
KeyError: 'children'

### ISSUE THREAD

**Issue by lukeshortal** [kjoconnor/pytinybeans#2]
Hi kjoconnor,

Not sure if it's an issue or I'm a dummy pants, but I'm getting the following error when I try and run your example code:
KeyError: 'children'

I'm not using from pytinybeans import PyTinybeans, I'm just copy/pasting the whole library because I believe I need to use my own IOS_CLIENT_ID (and then just instantiate with tb = PyTinybeans()) Am I right or wrong on this?

tb.CLIENT_ID returns the client ID I defined.
tb.logged_in returns FALSE until I login, then returns TRUE. 

So I think it's mostly still working, but maybe TinyBeans have updated thier application.
If you have any ideas, please let me know on how I might find this by combing through the HTML. Happy to give it a crack to update the library if required.

Thanks,

Luke
(and if you case you can't tell, I'm faily noob with Python)

**Comment by kjoconnor** [comment]
I'm fairly certain you do not need your own `IOS_CLIENT_ID`. Unless Tinybeans have changed it between now and when I last committed it you shouldn't need to use your own.

I just tested it out and it still works for me. I'd suggest installing this library via `pip install pytinybeans` rather than trying to copy/paste. If you still have problems, paste your code here or in a gist and I'll take a look.

**Comment by kjoconnor** [comment]
I'm fairly certain you do not need your own `IOS_CLIENT_ID`. Unless Tinybeans have changed it between now and when I last committed it you shouldn't need to use your own.

I just tested it out and it still works for me. I'd suggest installing this library via `pip install pytinybeans` rather than trying to copy/paste. If you still have problems, paste your code here or in a gist and I'll take a look.

**Comment by lukeshortal** [comment]
Thanks for the reply. I still couldn't get it to work as described, but I
did get a backup of my archive using a combination of your code and another
library. All good.

Thanks.
*Luke*
